title: Computer Science Notes
email: geoffchoy@outlook.com
description: >
  Computer Science notes that I've had for a while.

url: "http://localhost:4000"
baseurl: ""
gh_url: "https://burrt.github.io/compsci-docs/"

github_username: burrt

markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

collections:
  v1:
    name: "v1 Docs"
    site_section: true
    output: true
    permalink: /v1/:path/
    prefix: "/v1"
    selectorName: "v1"

defaults:
  - scope:
      path: ""
      type: "v1"
    values:
      lang: "en"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
