title: Computer Science Notes
author: Geoffrey Choy
email: geoffchoy@outlook.com
description: >
  Computer Science notes that I've had for a while.

url: "https://burrt.github.io/compsci-docs/"
baseurl: "/compsci-docs"

github_username: burrt
repository: "burrt/compsci-docs"

google_analytics: UA-104494941-5

markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  v1:
    name: "v1 Docs"
    site_section: true
    output: true
    permalink: /v1/:path/
    prefix: "/v1"
    selectorName: "v1"

defaults:
  - scope:
      path: ""
      type: "v1"
    values:
      lang: "en"

# SEO
social:
  name: Geoffrey Choy
  links:
    - https://www.linkedin.com/in/geoffrey-choy

logo: /favicons/favicon-96x96.png

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
